---
title: "Crawling_Hsinchu7-11"
author: "Perilium"
date: "2018年10月6日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r run}
library(rvest)
raw <- read_html("http://www.319papago.idv.tw/lifeinfo/7-11/7-11-300-1.html")

raw1 <- html_nodes(raw, "h2+ table td:nth-child(1)") %>% html_text(raw)
raw2 <- html_nodes(raw, "h2+ table td:nth-child(2)") %>% html_text(raw)
raw3 <- html_nodes(raw, "h2+ table td:nth-child(3)") %>% html_text(raw)
raw4 <- html_nodes(raw, "h2+ table td:nth-child(4)") %>% html_text(raw)
need <- data.frame(raw1,raw2,raw3,raw4)

need
```

```{r run2}
raw <- read_html("http://www.319papago.idv.tw/lifeinfo/7-11/7-11-300-2.html")

raw1 <- html_nodes(raw, "h2+ table td:nth-child(1)") %>% html_text(raw)
raw2 <- html_nodes(raw, "h2+ table td:nth-child(2)") %>% html_text(raw)
raw3 <- html_nodes(raw, "h2+ table td:nth-child(3)") %>% html_text(raw)
raw4 <- html_nodes(raw, "h2+ table td:nth-child(4)") %>% html_text(raw)
need <- data.frame(raw1,raw2,raw3,raw4)

need
```

```{r run3}
raw <- read_html("http://www.319papago.idv.tw/lifeinfo/7-11/7-11-300-3.html")

raw1 <- html_nodes(raw, "h2+ table td:nth-child(1)") %>% html_text(raw)
raw2 <- html_nodes(raw, "h2+ table td:nth-child(2)") %>% html_text(raw)
raw3 <- html_nodes(raw, "h2+ table td:nth-child(3)") %>% html_text(raw)
raw4 <- html_nodes(raw, "h2+ table td:nth-child(4)") %>% html_text(raw)
need <- data.frame(raw1,raw2,raw3,raw4)

need
```
