---
title: "Hsinchu_7-11"
author: "Perilium"
date: "2018年10月4日"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
此次挑戰使用leaflet製出互動式地圖，主題為新竹市7-11的分布圖，標籤內容附上各門市的電話號碼。
## 載入資料庫
```{r inside}
library(leaflet)
```

## 載入地圖、座標，標上地圖點
利用Crawling_7-11address.Rmd 將新竹市的7-11相關資料抓下來，

利用座標轉換網站`http://gps.uhooamber.com/address-to-lat-lng.html `轉換成座標後，將兩個資料製成csv檔，之後在地圖上標上點即完成

按進標籤後，即可看到門市電話地址。

```{r map}
dat <- read.csv("https://perilium.github.io/NTU-CSX4001/Week_4/hw_4/map/7-11raw.csv")
for(i in c(1:134)){
  dat$content[i] <- paste("門市:",dat$Name[i],"<br/> 電話:",dat$Tel[i],"<br/>地址：",dat$Add[i],sep="")

}
```
由於資料量太大，故分為北區、東區(一)、東區(二)、香山區三個地圖。

### 此為北區地圖
```{r North}
leaflet(dat[1:30,]) %>% addTiles() %>%
  addMarkers(~Lon,~Lat, popup = ~content)
```
### 此為東區(一)地圖
```{r East}
leaflet(dat[31:51,]) %>% addTiles() %>%
  addMarkers(~Lon,~Lat, popup = ~content)
```
### 此為東區(二)地圖
```{r North}
leaflet(dat[94:113,]) %>% addTiles() %>%
  addMarkers(~Lon,~Lat, popup = ~content)
```
### 此為香山區地圖
```{r North}
leaflet(dat[115:134,]) %>% addTiles() %>%
  addMarkers(~Lon,~Lat, popup = ~content)
```
